# config.yaml
host:
  name: "chuk-mcp-virtual-fs"
  log_level: "INFO"

server:
  type: "stdio"  # or "websocket" if you prefer network-based communication

mcp_servers:
  virtual_fs:
    enabled: true
    location: "."
    tools:
      enabled: true
      module: "chuk_mcp_virtual_fs.tools"